import { useState, useRef } from "react";
import { AppLayout } from "@/components/layout/app-layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { BookMarked, Printer, ClipboardCopy, ArrowLeft, CheckCircle2 } from "lucide-react";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";

const FORMATS = ["Paperback", "Hardcover", "eBook (PDF)", "eBook (EPUB)"];
const LANGUAGES = ["English", "Yoruba", "Igbo", "Hausa", "Pidgin English", "French", "Portuguese", "Arabic"];
const EDITIONS = ["1st Edition", "2nd Edition", "3rd Edition", "4th Edition", "5th Edition", "Revised Edition", "Updated Edition"];
const COUNTRIES = ["Nigeria", "Ghana", "Kenya", "South Africa", "United Kingdom", "United States", "Canada", "Australia"];

const BISAC_CATEGORIES = [
  { code: "FIC000000", label: "Fiction / General" },
  { code: "FIC014000", label: "Fiction / Historical" },
  { code: "FIC019000", label: "Fiction / Literary" },
  { code: "FIC027000", label: "Fiction / Romance" },
  { code: "FIC028000", label: "Fiction / Science Fiction" },
  { code: "NON000000", label: "Non-Fiction / General" },
  { code: "BIO000000", label: "Biography & Autobiography / General" },
  { code: "BUS000000", label: "Business & Economics / General" },
  { code: "BUS016000", label: "Business & Economics / Entrepreneurship" },
  { code: "EDU000000", label: "Education / General" },
  { code: "REL000000", label: "Religion / General" },
  { code: "REL012000", label: "Religion / Christian Life / General" },
  { code: "SEL000000", label: "Self-Help / General" },
  { code: "SEL016000", label: "Self-Help / Personal Growth / Success" },
  { code: "HEA000000", label: "Health & Fitness / General" },
  { code: "POL000000", label: "Political Science / General" },
  { code: "SOC000000", label: "Social Science / General" },
  { code: "MED000000", label: "Medical / General" },
  { code: "LAW000000", label: "Law / General" },
  { code: "JUV000000", label: "Juvenile Fiction / General" },
  { code: "JNF000000", label: "Juvenile Nonfiction / General" },
];

interface Fields {
  title: string; subtitle: string; authors: string; editor: string;
  publisher: string; publisherAddress: string; year: string;
  format: string; category: string; description: string;
  pages: string; language: string; edition: string; country: string;
  contactName: string; contactEmail: string; contactPhone: string;
}

const EMPTY: Fields = {
  title: "", subtitle: "", authors: "", editor: "",
  publisher: "", publisherAddress: "", year: "",
  format: "", category: "", description: "",
  pages: "", language: "English", edition: "1st Edition",
  country: "Nigeria", contactName: "", contactEmail: "", contactPhone: "",
};

function DataSheet({ f }: { f: Fields }) {
  const bisac = BISAC_CATEGORIES.find((b) => b.code === f.category);
  const today = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  return (
    <div className="font-mono text-sm leading-relaxed space-y-4 p-8 bg-white border text-gray-900 print:p-0 print:border-0">
      <div className="text-center space-y-1 pb-4 border-b-2 border-gray-900">
        <p className="font-bold text-lg tracking-widest uppercase">ISBN Application Data Sheet</p>
        <p className="text-xs text-gray-500">Generated by Etscript · {today}</p>
      </div>

      <Section title="Title Information">
        <Row label="Title" value={f.title || "—"} />
        <Row label="Subtitle" value={f.subtitle || "N/A"} />
        <Row label="Edition" value={f.edition || "1st Edition"} />
      </Section>

      <Section title="Contributor Information">
        <Row label="Author(s)" value={f.authors || "—"} />
        <Row label="Editor(s)" value={f.editor || "N/A"} />
      </Section>

      <Section title="Publication Details">
        <Row label="Publisher" value={f.publisher || "—"} />
        <Row label="Publisher Address" value={f.publisherAddress || "—"} />
        <Row label="Year of Publication" value={f.year || "—"} />
        <Row label="Format / Binding" value={f.format || "—"} />
        <Row label="Estimated Page Count" value={f.pages || "—"} />
        <Row label="Language" value={f.language || "English"} />
        <Row label="Country of Publication" value={f.country || "Nigeria"} />
      </Section>

      <Section title="Subject Classification">
        <Row label="Primary Category" value={bisac?.label ?? f.category ?? "—"} />
        <Row label="BISAC Code" value={bisac?.code ?? "—"} />
      </Section>

      <Section title="Description / Back-Cover Copy">
        <p className="mt-1 whitespace-pre-wrap text-gray-700">{f.description || "—"}</p>
      </Section>

      <Section title="Contact Information">
        <Row label="Contact Name" value={f.contactName || "—"} />
        <Row label="Email" value={f.contactEmail || "—"} />
        <Row label="Phone" value={f.contactPhone || "—"} />
      </Section>

      <div className="pt-4 border-t text-xs text-gray-400 text-center">
        Submit this data sheet to your national ISBN agency. In Nigeria: Nigerian ISBN Agency (NAN) · nan.gov.ng
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="font-bold uppercase tracking-widest text-xs text-gray-500 mb-2">{title}</p>
      <div className="space-y-1 pl-2 border-l-2 border-gray-200">{children}</div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2">
      <span className="text-gray-500 shrink-0 w-44">{label}:</span>
      <span className="font-medium text-gray-900">{value}</span>
    </div>
  );
}

export default function IsbnPrepPage() {
  const [fields, setFields] = useState<Fields>(EMPTY);
  const [showPreview, setShowPreview] = useState(false);
  const sheetRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  const set = (k: keyof Fields) => (v: string) => setFields((f) => ({ ...f, [k]: v }));
  const onInput = (k: keyof Fields) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => set(k)(e.target.value);

  const isReady = !!fields.title && !!fields.authors && !!fields.publisher && !!fields.year;

  const handleCopy = async () => {
    if (!sheetRef.current) return;
    const text = sheetRef.current.innerText;
    await navigator.clipboard.writeText(text);
    toast({ title: "Copied to clipboard" });
  };

  const handlePrint = () => window.print();

  return (
    <AppLayout title="ISBN Preparation Tool">
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="flex items-center gap-3">
          <Link href="/tools">
            <Button variant="ghost" size="sm" className="gap-1.5 text-muted-foreground">
              <ArrowLeft className="w-4 h-4" /> Tools
            </Button>
          </Link>
        </div>

        <div className="flex items-start gap-3">
          <BookMarked className="w-7 h-7 text-primary mt-0.5 shrink-0" />
          <div>
            <h1 className="text-2xl font-serif font-medium">ISBN Preparation Tool</h1>
            <p className="text-muted-foreground text-sm mt-1">
              Fill in your book's details and generate a data sheet for your national ISBN agency.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Form */}
          <div className="space-y-6">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base font-semibold">Title Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Field label="Title *">
                  <Input placeholder="The Path Forward" value={fields.title} onChange={onInput("title")} />
                </Field>
                <Field label="Subtitle">
                  <Input placeholder="A Guide to Success" value={fields.subtitle} onChange={onInput("subtitle")} />
                </Field>
                <Field label="Edition">
                  <Select value={fields.edition} onValueChange={set("edition")}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{EDITIONS.map((e) => <SelectItem key={e} value={e}>{e}</SelectItem>)}</SelectContent>
                  </Select>
                </Field>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base font-semibold">Contributors</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Field label="Author(s) *" hint="Full names, comma-separated">
                  <Input placeholder="Emeka Okafor, Ngozi Adeyemi" value={fields.authors} onChange={onInput("authors")} />
                </Field>
                <Field label="Editor(s)" hint="If applicable">
                  <Input placeholder="Dr. James Eze" value={fields.editor} onChange={onInput("editor")} />
                </Field>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base font-semibold">Publication Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Field label="Publisher Name *">
                  <Input placeholder="Sunrise Books Nigeria" value={fields.publisher} onChange={onInput("publisher")} />
                </Field>
                <Field label="Publisher Address">
                  <Input placeholder="12 Lagos Street, Abuja, FCT" value={fields.publisherAddress} onChange={onInput("publisherAddress")} />
                </Field>
                <div className="grid grid-cols-2 gap-3">
                  <Field label="Year *">
                    <Input placeholder="2026" value={fields.year} onChange={onInput("year")} />
                  </Field>
                  <Field label="Pages">
                    <Input placeholder="256" type="number" value={fields.pages} onChange={onInput("pages")} />
                  </Field>
                </div>
                <Field label="Format">
                  <Select value={fields.format} onValueChange={set("format")}>
                    <SelectTrigger><SelectValue placeholder="Select format…" /></SelectTrigger>
                    <SelectContent>{FORMATS.map((f) => <SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent>
                  </Select>
                </Field>
                <div className="grid grid-cols-2 gap-3">
                  <Field label="Language">
                    <Select value={fields.language} onValueChange={set("language")}>
                      <SelectTrigger><SelectValue /></SelectTrigger>
                      <SelectContent>{LANGUAGES.map((l) => <SelectItem key={l} value={l}>{l}</SelectItem>)}</SelectContent>
                    </Select>
                  </Field>
                  <Field label="Country">
                    <Select value={fields.country} onValueChange={set("country")}>
                      <SelectTrigger><SelectValue /></SelectTrigger>
                      <SelectContent>{COUNTRIES.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent>
                    </Select>
                  </Field>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base font-semibold">Subject & Description</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Field label="Subject Category">
                  <Select value={fields.category} onValueChange={set("category")}>
                    <SelectTrigger><SelectValue placeholder="Select category…" /></SelectTrigger>
                    <SelectContent>
                      {BISAC_CATEGORIES.map((b) => (
                        <SelectItem key={b.code} value={b.code}>{b.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </Field>
                <Field label="Back-Cover Description" hint="~100 words max">
                  <Textarea
                    placeholder="A compelling overview of your book…"
                    rows={4}
                    value={fields.description}
                    onChange={onInput("description")}
                  />
                </Field>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-base font-semibold">Contact Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <Field label="Contact Name">
                  <Input placeholder="Emeka Okafor" value={fields.contactName} onChange={onInput("contactName")} />
                </Field>
                <Field label="Email">
                  <Input type="email" placeholder="author@email.com" value={fields.contactEmail} onChange={onInput("contactEmail")} />
                </Field>
                <Field label="Phone">
                  <Input placeholder="+234 800 000 0000" value={fields.contactPhone} onChange={onInput("contactPhone")} />
                </Field>
              </CardContent>
            </Card>

            <Button
              className="w-full gap-2"
              disabled={!isReady}
              onClick={() => setShowPreview(true)}
            >
              <CheckCircle2 className="w-4 h-4" />
              Generate Data Sheet
            </Button>
            {!isReady && (
              <p className="text-xs text-muted-foreground text-center">
                Fill in Title, Author(s), Publisher and Year to generate the data sheet.
              </p>
            )}
          </div>

          {/* Preview */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide">Data Sheet Preview</h2>
              {showPreview && (
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" className="gap-1.5" onClick={handleCopy}>
                    <ClipboardCopy className="w-3.5 h-3.5" /> Copy
                  </Button>
                  <Button variant="outline" size="sm" className="gap-1.5" onClick={handlePrint}>
                    <Printer className="w-3.5 h-3.5" /> Print
                  </Button>
                </div>
              )}
            </div>

            {showPreview ? (
              <div ref={sheetRef} className="rounded-lg overflow-hidden shadow border">
                <DataSheet f={fields} />
              </div>
            ) : (
              <div className="rounded-lg border-2 border-dashed border-border h-64 flex flex-col items-center justify-center text-center p-8 gap-3">
                <BookMarked className="w-8 h-8 text-muted-foreground/40" />
                <p className="text-sm text-muted-foreground">
                  Fill in the form and click "Generate Data Sheet" to see your preview here.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </AppLayout>
  );
}

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label className="text-sm">
        {label}
        {hint && <span className="font-normal text-muted-foreground ml-1">— {hint}</span>}
      </Label>
      {children}
    </div>
  );
}
